org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false
org.gradle.java.home=C:/Program Files/BellSoft/LibericaJDK-25

loader_version=0.19.5
loom_version=1.17-SNAPSHOT
fabric_api_version=0.150.0+26.1.2

mod_version=1.6.5
maven_group=nv.navineclient
navine_target=26.3
