minecraft_version=26.2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT
fabric_api_version=0.161.0+26.2
java_version=25
minecraft_depends=>=26.2 <26.3
archives_suffix=26.2
supported=true
note=Native Minecraft 26.2 build
